const mockMutation = () => ({
  mutate: (...args: any[]) => {},
  mutateAsync: async (...args: any[]) => {},
  isLoading: false,
  isPending: false,
});

export const trpc = {
  useUtils: () => ({
    cv: {
      getProfile: { invalidate: async () => {}, fetch: async (...args: any[]) => null },
      getExperiences: { invalidate: async () => {}, fetch: async (...args: any[]) => [] },
      getEducation: { invalidate: async () => {}, fetch: async (...args: any[]) => [] },
      getSkills: { invalidate: async () => {}, fetch: async (...args: any[]) => [] },
      getTemplates: { invalidate: async () => {}, fetch: async (...args: any[]) => [] },
      exportJson: { invalidate: async () => {}, fetch: async (...args: any[]) => null },
    },
    portfolio: {
      getProjectsByUser: { invalidate: async () => {}, fetch: async (...args: any[]) => [] },
      getBlogPostsByUser: { invalidate: async () => {}, fetch: async (...args: any[]) => [] },
      getSettings: { invalidate: async () => {}, fetch: async (...args: any[]) => null },
    },
  }),
  cv: {
    getProfile: { useQuery: (...args: any[]) => ({ data: null, isLoading: true }) },
    getExperiences: { useQuery: (...args: any[]) => ({ data: [], isLoading: true }) },
    getEducation: { useQuery: (...args: any[]) => ({ data: [], isLoading: true }) },
    getSkills: { useQuery: (...args: any[]) => ({ data: [], isLoading: true }) },
    getTemplates: { useQuery: (...args: any[]) => ({ data: [], isLoading: true }) },
    upsertProfile: { useMutation: mockMutation },
    createExperience: { useMutation: mockMutation },
    updateExperience: { useMutation: mockMutation },
    deleteExperience: { useMutation: mockMutation },
    createEducation: { useMutation: mockMutation },
    updateEducation: { useMutation: mockMutation },
    deleteEducation: { useMutation: mockMutation },
    createSkill: { useMutation: mockMutation },
    updateSkill: { useMutation: mockMutation },
    deleteSkill: { useMutation: mockMutation },
    createTemplate: { useMutation: mockMutation },
    updateTemplate: { useMutation: mockMutation },
    deleteTemplate: { useMutation: mockMutation },
    exportJson: { useQuery: (...args: any[]) => ({ data: null, isLoading: true }) },
    exportJsonForAi: { useQuery: (...args: any[]) => ({ data: null, isLoading: true }) },
    importJson: { useMutation: mockMutation },
  },
  portfolio: {
    getProjectsByUser: { useQuery: (...args: any[]) => ({ data: [], isLoading: true }) },
    getBlogPostsByUser: { useQuery: (...args: any[]) => ({ data: [], isLoading: true }) },
    getSettings: { useQuery: (...args: any[]) => ({ data: null, isLoading: true }) },
    createProject: { useMutation: mockMutation },
    updateProject: { useMutation: mockMutation },
    deleteProject: { useMutation: mockMutation },
    createBlogPost: { useMutation: mockMutation },
    updateBlogPost: { useMutation: mockMutation },
    deleteBlogPost: { useMutation: mockMutation },
    updateSettings: { useMutation: mockMutation },
  },
};
